In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import tensorflow as tf
from sklearn.decomposition import PCA

In [11]:
train = pd.read_csv('data/train.csv')

In [19]:
letters_sorted = np.sort(train['letter'].unique())
for letter in letters_sorted:
    digits = train[train['letter'] == letter]['digit']
    count = digits.value_counts()
    tmp_df = pd.DataFrame({letter:count})
    if letter == 'A':
        df = tmp_df
    else:
        df = pd.concat([df, tmp_df], axis=1)

In [20]:
df

,A,B,C,D,E,F,G,H,I,J,...,Q,R,S,T,U,V,W,X,Y,Z
0,5,5,12,6,4,4,11,10,7,3,...,7,5,7,8,7,4,7,7,10,12
1,3,2,15,10,6,13,5,6,5,8,...,11,10,12,5,6,6,6,8,2,10
2,9,8,4,12,9,7,9,16,5,8,...,13,4,7,5,11,11,11,10,12,7
3,1,7,6,15,7,8,7,10,8,15,...,7,10,9,5,6,6,3,7,10,10
4,7,13,5,4,11,8,11,5,5,8,...,7,7,10,5,11,8,9,5,6,8
5,5,4,7,7,8,6,12,12,4,9,...,10,10,8,9,15,9,9,12,13,16
6,8,12,6,7,8,13,12,7,8,5,...,6,9,6,15,7,5,7,5,11,9
7,11,7,6,5,2,7,7,7,10,3,...,6,14,6,5,2,10,7,7,7,11
8,8,7,5,5,3,4,8,8,8,5,...,7,6,8,12,6,6,5,9,11,3
9,15,6,8,5,8,10,5,8,4,3,...,8,6,3,13,14,8,5,9,4,5

In [21]:
np.sum(df['A'].values)

72